@startuml
[*] ---> read_first_byte

read_first_byte --> [*]: char:eof-object?
read_first_byte -down-> P: correct-first-byte?
read_first_byte --> [*]: throw-wrong-first-byte-error

P: Read the "P" letter
P --> [*]: char:eof-object? -> throw-unexpected-eof-error
P -down-> N: char:letter-P?
P --> [*]: throw-unexpected-byte-error

N: Read the "N" letter
N --> [*]: char:eof-object? -> throw-unexpected-eof-error
N -down-> G: char:letter-N?
N --> [*]: throw-unexpected-byte-error

G: Read the "G" letter
G --> [*]: char:eof-object? -> throw-unexpected-eof-error
G -down-> CR: char:letter-G?
G --> [*]: throw-unexpected-byte-error

CR: Read the carriage return (CR)
CR ---> [*]: char:eof-object? -> throw-unexpected-eof-error
CR -down-> LF: char:cr?
CR --> [*]: throw-unexpected-byte-error

LF: Read the linefeed (LF)
LF ---> [*]: char:eof-object? -> throw-unexpected-eof-error
LF -down-> ctrl_z: char:lf?
LF ---> [*]: throw-unexpected-byte-error

ctrl_z --> [*]: char:eof-object? -> throw-unexpected-eof-error
ctrl_z -down-> final_LF: char:sub?
ctrl_z --> [*]: throw-unexpected-byte-error

final_LF ---> [*]: char:eof-object? -> throw-unexpected-eof-error
final_LF -down-> [*]: char:lf?
final_LF ---> [*]: throw-unexpected-byte-error
@enduml
