@startuml
title PlantUML <https://plantuml.com> Reader Finite-State Machine.\nThis FSM is a part of Guile State-Machine Compiler (Guile-SMC)\n<https://github.com/artyom-poptsov/guile-smc>

' Entry point
[*] -> search_start_tag

search_start_tag --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
search_start_tag --> check_top_multiline_comment_begin: char:solidus?
search_start_tag --> read_start_tag: char:at-symbol? -> push-event-to-buffer
search_start_tag -> search_start_tag

read_start_tag: Read the start @startuml tag and check it for errors
read_start_tag --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_start_tag --> read: char:space? -> validate-start-tag
read_start_tag --> read: char:newline? -> validate-start-tag
read_start_tag -> read_start_tag: guard:#t -> push-event-to-buffer

check_top_multiline_comment_begin -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
check_top_multiline_comment_begin --> read_top_multiline_comment: char:single-quote?
check_top_multiline_comment_begin --> [*]: throw-syntax-error

read_top_multiline_comment: Read a multiline comment before the start tag.
read_top_multiline_comment -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_top_multiline_comment -> check_top_multiline_comment_end: char:single-quote?
read_top_multiline_comment -> read_top_multiline_comment

check_top_multiline_comment_end -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
check_top_multiline_comment_end --> search_start_tag: char:solidus?
check_top_multiline_comment_end --> read_top_multiline_comment

read: Read the PlantUML transition table.
read -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read --> check_multiline_comment_begin: char:solidus?
read --> read_end_tag: char:at-symbol? -> push-event-to-buffer
read --> read_skip_comment: char:single-quote?
read --> read_state: char:left-square-bracket?
read --> read_word: char:letter? -> push-event-to-buffer
read -> read

check_multiline_comment_begin -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
check_multiline_comment_begin --> read_multiline_comment: char:single-quote?
check_multiline_comment_begin --> [*]: throw-syntax-error

read_multiline_comment: Read a multiline comment before the start tag.
read_multiline_comment -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_multiline_comment -> check_multiline_comment_end: char:single-quote?
read_multiline_comment -> read_multiline_comment

check_multiline_comment_end -> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
check_multiline_comment_end --> read: char:solidus?
check_multiline_comment_end --> read_multiline_comment

read_end_tag: Read and check the @enduml tag.
read_end_tag:
read_end_tag: exit-action: validate-end-tag
read_end_tag --> [*]: char:eof-object?
read_end_tag --> [*]: char:newline?
read_end_tag --> [*]: char:space?
read_end_tag ->  read_end_tag: guard:#t -> push-event-to-buffer

read_skip_comment: Skip commentaries that are written between stanzas.
read_skip_comment --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_skip_comment --> read: char:newline?
read_skip_comment ->  read_skip_comment

read_word: Read a word.
read_word --> [*]: char:eof-object?  -> throw-unexpected-end-of-file-error
read_word --> read_title: title? -> clear-buffer
read_word --> read_legend: legend? -> clear-buffer
read_word --> skip_hide_block: hide? -> clear-buffer
read_word --> read_state_description: char:colon? -> push-buffer-to-stanza
read_word --> search_state_transition: char:space? -> push-buffer-to-stanza
read_word -> read_word: guard:#t -> push-event-to-buffer

skip_hide_block: Skip the "hide" block in a state diagram.
skip_hide_block --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
skip_hide_block -> read: char:newline?
skip_hide_block -> skip_hide_block

read_legend: Read diagram legend.
read_legend --> [*]: char:eof-object? -> throw-no-endlegend-error
read_legend --> read: legend-end? -> clear-buffer
read_legend -> read_legend: legend-event-source? -> set-event-source
read_legend -> read_legend: legend-pre-action? -> set-pre-action
read_legend -> read_legend: legend-post-action? -> set-post-action
read_legend -> read_legend: char:newline? -> clear-buffer
read_legend -> read_legend: guard:#t -> push-event-to-buffer

read_title: Read a diagram title.
read_title --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_title --> read: char:newline? -> add-description
read_title -> read_title: guard:#t -> push-event-to-buffer

read_state: Read a PlantUML stanza.
read_state --> [*]: char:eof-object?
read_state --> [*]: char:newline? -> throw-syntax-error
read_state --> search_state_transition: char:right-square-bracket? -> push-buffer-to-stanza
read_state --> search_state_transition: char:space? -> push-buffer-to-stanza
read_state --> read_state_description: char:colon? -> push-buffer-to-stanza
read_state -> read_state: guard:#t -> push-event-to-buffer

search_state_transition: Check if a state has a transition.
search_state_transition --> [*]: char:eof-object?
search_state_transition --> read_state_description: char:colon?
search_state_transition --> read_state_right_arrow: char:hyphen-minus?
search_state_transition --> read_state_left_arrow: char:less-than-sign?
search_state_transition ->  search_state_transition

read_state_description: Read a state description if it is present.
read_state_description --> [*]: char:eof-object?
read_state_description --> read: char:newline? -> process-state-description
read_state_description ->  read_state_description: guard:#t -> push-event-to-buffer

read_state_right_arrow: Read a right arrow that indicates a transition.
read_state_right_arrow --> [*]: char:eof-object?
read_state_right_arrow --> search_state_transition_to: char:space?
read_state_right_arrow -> read_state_right_arrow

search_state_transition_to: Search for a state that the current state transitions to.
search_state_transition_to --> [*]: char:eof-object?
search_state_transition_to --> read_state_transition_to: char:letter? -> push-event-to-buffer
search_state_transition_to --> read_state_transition_to: char:left-square-bracket?
search_state_transition_to -> search_state_transition_to

read_state_transition_to: Read a state that the current state transitions to.
read_state_transition_to --> [*]: char:eof-object?
read_state_transition_to --> read_state_transition_to: char:right-square-bracket?
read_state_transition_to --> search_state_transition_guard: char:colon? -> push-buffer-to-stanza
read_state_transition_to --> read: char:newline? -> add-state-transition
read_state_transition_to -> read_state_transition_to: guard:#t -> push-event-to-buffer

search_state_transition_guard: Check if the transition has a guard.
search_state_transition_guard --> [*]: char:eof-object?
search_state_transition_guard --> read_state_transition_guard: char:letter? -> push-event-to-buffer
search_state_transition_guard -> search_state_transition_guard

read_state_transition_guard: Read a state transition guard.
read_state_transition_guard --> [*]: char:eof-object?
read_state_transition_guard --> search_state_action_arrow: char:space? -> push-buffer-to-stanza
read_state_transition_guard --> read: char:newline? -> add-state-transition
read_state_transition_guard -> read_state_transition_guard: guard:#t -> push-event-to-buffer

search_state_action_arrow: Check if a transition has an attached action.
search_state_action_arrow --> [*]: char:eof-object?
search_state_action_arrow --> read: char:newline?
search_state_action_arrow --> read_state_action_arrow: char:hyphen-minus?
search_state_action_arrow -> search_state_action_arrow

read_state_action_arrow: Read and skip the action arrow.
read_state_action_arrow --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_state_action_arrow --> [*]: char:newline?
read_state_action_arrow --> search_state_transition_action: char:more-than-sign?

search_state_transition_action: Check if an action is present after the arrow.
search_state_transition_action: Issue an error if it is not.
search_state_transition_action --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
search_state_transition_action --> read_state_transition_action: char:letter? -> push-event-to-buffer
search_state_transition_action --> [*]: char:newline?
search_state_transition_action -> search_state_transition_action

read_state_transition_action: Read the state transition action.
read_state_transition_action --> [*]: char:eof-object? -> throw-unexpected-end-of-file-error
read_state_transition_action --> read: char:newline? -> add-state-transition
read_state_transition_action -> read_state_transition_action: guard:#t -> push-event-to-buffer
@enduml
