@startuml
[*] --> DEFAULT
DEFAULT: Count parenthesis.
DEFAULT --> [*]: guard:eof-object? -> action:validate
DEFAULT --> COMMENT: guard:semicolon?
DEFAULT --> STRING: guard:double-quote?
DEFAULT --> DEFAULT: guard:#t -> action:count

COMMENT: Skip a comment.
COMMENT --> DEFAULT: guard:newline?
COMMENT --> COMMENT

STRING: Skip a string.
STRING --> DEFAULT: guard:double-quote?
STRING -> STRING
@enduml
