@startuml
[*] --> DEFAULT
DEFAULT: Count parenthesis.
DEFAULT --> [*]: char:eof-object? -> action:validate
DEFAULT --> COMMENT: char:semicolon?
DEFAULT --> STRING: char:double-quote?
DEFAULT --> DEFAULT: guard:#t -> action:count

COMMENT: Skip a comment.
COMMENT --> DEFAULT: char:newline?
COMMENT --> COMMENT

STRING: Skip a string.
STRING --> DEFAULT: char:double-quote?
STRING -> STRING
@enduml
