name: Ubuntu/Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
              automake \
              autoconf \
              guile-3.0 \
              guile-3.0-dev \
              guile-library \
              texinfo \
              bsdutils \
              help2man
        
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Build
        run: make -j$(nproc)

      - name: Run tests
        run: make -j$(nproc) check
