---
# File : guix.yml

name: Guix/Guile 3.0

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86_64-linux-gnu:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Guix cache"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/guix"
          # Guix cashed once a day; the first build will be slow but the
          # subsequent builds on the current day will be faster.
          key: "guix-cache-x86-${{ steps.date.outputs.date }}"
          restore-keys: |
            guix-cache-x86-
      - name: "Install Guix"
        uses: "PromyLOPh/guix-install-action@v1"
      - name: "Ensure no locale warning"
        run: |
          test -z "$(guix --version 2>&1 >/dev/null)"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Build project guile-smc"
        run: |
          guix build --file=guix.scm
  aarch64-linux-gnu:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Guix cache"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/guix"
          # use a key that (almost) never matches
          key: "guix-cache-aarch64-${{ steps.date.outputs.date }}"
          restore-keys: |
            guix-cache-aarch64-
      - name: "Install Guix"
        uses: "PromyLOPh/guix-install-action@v1"
      - name: "Ensure no locale warning"
        run: |
          test -z "$(guix --version 2>&1 >/dev/null)"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Build project guile-smc"
        run: |
          guix build --target=aarch64-linux-gnu --file=guix.scm

# End of guix.yml
...
